# TRMNLP configuration
---
watch:
  - src
  - .trmnlp.yml

custom_fields:
  city_name: Barcelona
  location_key: 'accu:307297'
  temperature_unit: celsius

time_zone: Europe/Madrid
transform_runtime: enabled

variables:
  trmnl: {}
