# TRMNLP configuration
---
watch:
  - src
  - .trmnlp.yml

custom_fields:
  location: ''
  coordinates: ''
  temperature_unit: celsius

time_zone: Europe/Madrid
transform_runtime: enabled

variables:
  trmnl: {}
